### ISSUE TITLE
Add a dependency to InfyOm generator

### ISSUE THREAD

**Issue by shdpl** [EscolaLMS/Core#14]
There is an usage of ResponseUtil from InfyOm namespace, but core lacks dependency of it.
We should either remove the dependency or add a dependency to composer.json

https://github.com/EscolaLMS/Core/blob/9123e625c27b37bc3256c3c85b85a6c425599ea3/src/Http/Controllers/EscolaLmsBaseController.php#L10

**Comment by qunabu** [comment]
Duplicate of https://github.com/EscolaLMS/Core/issues/10
