### ISSUE TITLE
code covarage to low

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Core#21]
- [x] should be at least 60% 
- [ ] lets remove unused code

**Comment by qunabu** [comment]
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/214608/158390344-4e498798-91c4-4938-bf8b-1e1fea6f2f7b.png">


core should have cc close to 100%

**Comment by KrzysztofDziedziechEscolasoft** [comment]
CC is 93%
